FROM python:3.12-slim

RUN pip install \
    dagster \
    dagster-webserver \
    dagster-postgres \
    dagster-docker \
    psycopg2-binary

# Set $DAGSTER_HOME and copy configuration files
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME 