notion_views:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PGHOST', 'localhost') }}"
      port: "{{ env_var('PGPORT', '5432') | int }}"
      user: "{{ env_var('PGUSER', 'postgres') }}"
      password: "{{ env_var('PGPASSWORD', 'supersecret') }}"
      dbname: "{{ env_var('PGDATABASE', 'analytics') }}"
      schema: notion_views
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1 