{# Macro to generate mart SQL for a Notion database #}
{% macro generate_mart_sql(database_config) %}
{{
  config(
    materialized='table',
    schema='marts',
    alias=database_config.friendly_name ~ '_view'
  )
}}

-- Auto-generated mart for {{ database_config.friendly_name }}
-- This extracts common properties and makes them queryable

with staged_data as (
  select * 
  from {{ ref('stg_notion_universal') }}
  where database_name = '{{ database_config.friendly_name }}'
),

properties_extracted as (
  select 
    -- Core fields (same for all databases)
    page_id,
    created_time,
    last_edited_time,
    created_by,
    last_edited_by,
    
    -- Extract common property patterns
    -- Title/Name (try multiple common patterns)
    coalesce(
      raw_properties->>'properties__name__title',
      raw_properties->>'properties__title__title',
      raw_properties->>'properties__Name__title',
      raw_properties->>'properties__Title__title'
    ) as title,
    
    -- Status/State
    coalesce(
      raw_properties->>'properties__status__select__name',
      raw_properties->>'properties__Status__select__name',
      raw_properties->>'properties__state__select__name'
    ) as status,
    
    -- Categories/Tags
    coalesce(
      raw_properties->>'properties__category__id',
      raw_properties->>'properties__categories__id',
      raw_properties->>'properties__tags__id'
    ) as category_id,
    
    -- Dates
    coalesce(
      raw_properties->>'properties__date__date__start',
      raw_properties->>'properties__due_date__date__start',
      raw_properties->>'properties__deadline__date__start'
    )::timestamp as date_field,
    
    -- Description/Notes
    coalesce(
      raw_properties->>'properties__description__rich_text',
      raw_properties->>'properties__content__rich_text',
      raw_properties->>'properties__notes__rich_text'
    ) as description,
    
    -- Always include raw properties for custom extraction
    raw_properties
    
  from staged_data
)

select * from properties_extracted
{% endmacro %}


{# Macro to create a simple mart model file #}
{% macro create_mart_model_file(database_name) %}
  {% set file_content %}
-- This file was auto-generated by the create_mart_model_file macro
-- Feel free to customize it for {{ database_name }}-specific properties

{{ generate_mart_sql({"friendly_name": database_name}) }}
  {% endset %}
  
  {{ return(file_content) }}
{% endmacro %}


{# Macro to generate all mart views using run_query #}
{% macro generate_all_mart_views() %}
  {% set databases = var('notion_databases') %}
  
  {% for db in databases %}
    {% set view_sql %}
CREATE OR REPLACE VIEW {{ target.schema }}_marts.{{ db.friendly_name }}_view AS
WITH staged_data AS (
  SELECT * 
  FROM {{ target.schema }}_staging.stg_notion_universal
  WHERE database_name = '{{ db.friendly_name }}'
)
SELECT 
  page_id,
  created_time,
  last_edited_time,
  created_by,
  last_edited_by,
  
  -- Common properties
  coalesce(
    raw_properties->>'properties__name__title',
    raw_properties->>'properties__title__title'
  ) as title,
  
  raw_properties
FROM staged_data;
    {% endset %}
    
    {% if execute %}
      {% do run_query(view_sql) %}
      {{ log("Created mart view for " ~ db.friendly_name, info=True) }}
    {% endif %}
  {% endfor %}
{% endmacro %} 